In [2]:
# Question 11:

import numpy as np
import math

def gaussian(x, mean, variance):
    
    return (1.0/np.sqrt(2*math.pi*variance)) * np.exp(-(x-mean)**2 / (2*variance))

# Train data
x_train_group_0 = np.array([1.4, 1.0, 1.3, 1.9, 2.0, 1.8])
x_train_group_1 = np.array([3.0, 3.8, 4.1, 3.9, 4.2, 3.4])
print(len(x_train_group_0))
print(len(x_train_group_1))

6
6


In [3]:
mean_group_0 = x_train_group_0.mean()
var_group_0 = x_train_group_0.var()
print('mean group 0:', mean_group_0)
print('var group 0:', var_group_0)

mean_group_1 = x_train_group_1.mean()
var_group_1 = x_train_group_1.var()

print('mean group 1:', mean_group_1)
print('var group 1:', var_group_1)


mean group 0: 1.5666666666666667
var group 0: 0.1288888888888889
mean group 1: 3.733333333333333
var group 1: 0.1722222222222222


In [4]:
# Predict
x_test = np.array([[3.4]])

pdf_group_0_x = gaussian(x_test, mean_group_0, var_group_0)
pdf_group_1_x = gaussian(x_test, mean_group_1, var_group_1)

p0, p1 = 0.5, 0.5

total = pdf_group_0_x * 0.5 + pdf_group_1_x * 0.5
print('total', total)
# print('testing pdf group 0', pdf_group_0_x)
# print('testing pdf group 1', pdf_group_1_x)


# Normalize
pdf_group_0_x = pdf_group_0_x * p0
pdf_group_1_x = pdf_group_1_x * p1


print('pdf group 0:', pdf_group_0_x)
print('pdf group 1:', pdf_group_1_x)

total [[0.34813043]]
pdf group 0: [[1.20808206e-06]]
pdf group 1: [[0.34812922]]


In [5]:
# PLAY TENNIS CLASSIFIER

###############
# Create dataset
###############
import numpy as np

def create_train_dataset():
    data_string = [
        'Sunny Hot High Weak no',
        'Sunny Hot High Strong no',
        'Overcast Hot High Weak yes',
        'Rain Mild High Weak yes',
        'Rain Cool Normal Weak yes',
        'Rain Cool Normal Strong no',
        'Overcast Cool Normal Strong yes',
        'Overcast Mild High Weak no',
        'Sunny Cool Normal Weak yes',
        'Rain Mild Normal Weak yes'
    ]
    data = [string.split(' ') for string in data_string]

    return np.array(data)

train_data = create_train_dataset()
print(train_data)

[['Sunny' 'Hot' 'High' 'Weak' 'no']
 ['Sunny' 'Hot' 'High' 'Strong' 'no']
 ['Overcast' 'Hot' 'High' 'Weak' 'yes']
 ['Rain' 'Mild' 'High' 'Weak' 'yes']
 ['Rain' 'Cool' 'Normal' 'Weak' 'yes']
 ['Rain' 'Cool' 'Normal' 'Strong' 'no']
 ['Overcast' 'Cool' 'Normal' 'Strong' 'yes']
 ['Overcast' 'Mild' 'High' 'Weak' 'no']
 ['Sunny' 'Cool' 'Normal' 'Weak' 'yes']
 ['Rain' 'Mild' 'Normal' 'Weak' 'yes']]


In [15]:
# Step 2: Compute prior probabilities

def compute_prior_probabilities(train_data):
    y_unique = ['no', 'yes']
    
    # Create an array to store probablities
    prior_probs = np.zeros(len(y_unique))
    
    for i in range(len(y_unique)):
        target = y_unique[i]
        prior_probs[i] = np.sum(train_data[:, -1] == target) / len(train_data)

    return prior_probs


print(compute_prior_probabilities(train_data))
print("P(play tennis = No):", compute_prior_probabilities(train_data)[0])
print("P(play tennis = Yes):", compute_prior_probabilities(train_data)[1])



[0.4 0.6]
P(play tennis = No): 0.4
P(play tennis = Yes): 0.6


In [63]:
def compute_conditional_probability(train_data):
    y_unique = np.unique(train_data[:, -1])

    # Initialize condition probabilities
    conditional_probs = []
    
    # Store unique values of x for each column
    list_x_names = []
    
    # Find unique values for each column
    for i in range(train_data.shape[1] - 1): # i =index colum
        x_unique = np.unique(train_data[:, i])
        list_x_names.append(x_unique)

        # compute conditionla probs
        x_conditional_probs = np.zeros((len(y_unique), len(x_unique)))
        
        for j in range(len(y_unique)):
            for k in range(len(x_unique)):
                x_conditional_probs[j, k] = len(np.where((train_data[:, i] == x_unique[k]) &\
                                            (train_data[:, -1] == y_unique[j]))[0])\
                                            / len(np.where(train_data[:, -1] == y_unique[j])[0])
                                            
    
        conditional_probs.append(x_conditional_probs)

    return conditional_probs, list_x_names


train_data = create_train_dataset()
_, list_x_name = compute_conditional_probability(train_data)
print("x1 =", list_x_name[0])
print("x2 =", list_x_name[1])
print("x3 =", list_x_name[2])
print("x4 =", list_x_name[3])



x1 = ['Overcast' 'Rain' 'Sunny']
x2 = ['Cool' 'Hot' 'Mild']
x3 = ['High' 'Normal']
x4 = ['Strong' 'Weak']


In [ ]:
# switch dong thanh coit

In [64]:
def train_naive_bayes(train_data):
    # Step 1: compute prior probabilities
    prior_probs = compute_prior_probabilities(train_data)

    # Step 2: compute conditional probabilities
    conditional_probs, list_x_name = compute_conditional_probability(train_data)


    return prior_probs, conditional_probs, list_x_name


train_naive_bayes(train_data)

(array([0.4, 0.6]),
 [array([[0.25      , 0.25      , 0.5       ],
         [0.33333333, 0.5       , 0.16666667]]),
  array([[0.25      , 0.5       , 0.25      ],
         [0.5       , 0.16666667, 0.33333333]]),
  array([[0.75      , 0.25      ],
         [0.33333333, 0.66666667]]),
  array([[0.5       , 0.5       ],
         [0.16666667, 0.83333333]])],
 [array(['Overcast', 'Rain', 'Sunny'], dtype='<U8'),
  array(['Cool', 'Hot', 'Mild'], dtype='<U8'),
  array(['High', 'Normal'], dtype='<U8'),
  array(['Strong', 'Weak'], dtype='<U8')])

In [65]:
def get_index_from_value(feature_name, list_features):

    return np.where(list_features == feature_name)[0][0]


train_data = create_train_dataset()
conditional_probs, list_x_name = compute_conditional_probability(train_data)
outlook = list_x_name[0]

i1 = get_index_from_value('Overcast', outlook)
i2 = get_index_from_value('Rain', outlook)
i3 = get_index_from_value('Sunny', outlook)
print(i1, i2, i3)



0 1 2


In [59]:
print(conditional_probs)

[array([[0.25      , 0.25      , 0.5       ],
       [0.33333333, 0.5       , 0.16666667]]), array([[0.25      , 0.5       , 0.25      ],
       [0.5       , 0.16666667, 0.33333333]]), array([[0.75      , 0.25      ],
       [0.33333333, 0.66666667]]), array([[0.5       , 0.5       ],
       [0.16666667, 0.83333333]])]


In [69]:
index_yes = 1


print(round(conditional_probs[0][1, i3], 2))

0.17


In [72]:
x2 = get_index_from_value('Sunny', list_x_name[0])
print(conditional_probs[1][1, x2])

0.3333333333333333


In [62]:
def predict(x, list_x_name, prior_probs, conditional_probs):
    x1 = get_index_from_value(x[0], list_x_name[0])
    x2 = get_index_from_value(x[1], list_x_name[1])
    x3 = get_index_from_value(x[2], list_x_name[2])
    x4 = get_index_from_value(x[3], list_x_name[3])

    p0 = prior_probs[0] * conditional_probs[0][0, x1]\
                        * conditional_probs[1][0, x2]\
                        * conditional_probs[2][0, x3]\
                        * conditional_probs[3][0, x4]

    p1 = prior_probs[1] * conditional_probs[0][1, x1]\
                        * conditional_probs[1][1, x2]\
                        * conditional_probs[2][1, x3]\
                        * conditional_probs[3][1, x4]             
    
    if p0 > p1:
        y_pred = 'no', p0
    else:
        y_pred = 'yes', p0

    return y_pred


                        
    



x = ['Sunny', 'Cool', 'High', 'Strong']

prior_probs = compute_prior_probabilities(train_data)
print(predict(x, list_x_name, prior_probs, conditional_probs))

('no', 0.018750000000000003)
