In [2]:
import numpy as np


def compute_vector_length(vector):

    return np.linalg.norm(vector)


# v = np.array([2, 3])
# print(compute_vector_length(v) == np.sqrt(13))

vector = np.array([-2, 4, 9, 21])
result = compute_vector_length(vector)
print(round(result, 2))

23.28


In [3]:
# Dot product of 2 vectors
def compute_dot_product(v1, v2):
    return np.dot(v1, v2)

# Tests
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])

print(compute_dot_product(v1,v2))

4


In [4]:
x = np.arange(1, 5).reshape(2, 2)
k = np.array([1, 2])
print(x.dot(k))

[ 5 11]


In [6]:
x = np.array([
    [-1, 2],
    [3, -4]
])
k = np.array([1, 2])
print(x@k)
print(x.dot(k))

[ 3 -5]
[ 3 -5]


In [8]:
# Matrix and vector multiplication
def matrix_mult_vector(matrix, vector):

    return matrix.dot(vector)

# Tests

matrix = np.array([
    [-1, 1, 1],
    [0, -4, 9]
])
print(matrix)
vector = np.array([0, 2, 1])
print(vector)

print(matrix_mult_vector(matrix, vector))

[[-1  1  1]
 [ 0 -4  9]]
[0 2 1]
[3 1]


In [9]:
# Matrix and matrix multiplication
def matrix_mult_matrix(m1, m2):

    return np.matmul(m1, m2)

# Tests

m1 = np.array([
    [0, 1, 2],
    [2, -3, 1]
])
m2 = np.array([
    [1, -3],
    [6, 1],
    [0, -1]
])
print(m1)
print(m2)

print(matrix_mult_matrix(m1, m2))

[[ 0  1  2]
 [ 2 -3  1]]
[[ 1 -3]
 [ 6  1]
 [ 0 -1]]
[[  6  -1]
 [-16 -10]]


In [13]:
m1 = np.eye(3)
print(m1)

m2 = np.array([
    [1]*3,
    [2]*3,
    [3]*3
])

print(m2)

print(m1@m2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [24]:
m1 = np.eye(2)
print(m1, m1.shape)
m1 = np.reshape(m1, (-1, 4))[0]
print(m1)
print(type(m1))
m2 = np.array([
    [1]*4,
    [2]*4,
    [3]*4,
    [4]*4
])

print(m2)
print(m1@m2)

[[1. 0.]
 [0. 1.]] (2, 2)
[1. 0. 0. 1.]
<class 'numpy.ndarray'>
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
[5. 5. 5. 5.]


In [28]:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1, (-1, 4), "F")[0]
m2 = np.array([
    [1]*4,
    [2]*4,
    [3]*4,
    [4]*4
])
print(m1@m2)

[29 29 29 29]


In [21]:
# Inverse matrix

def inverse_matrix(m):
    det = np.linalg.det(m)

    return np.linalg.inv(m)

m = np.array([
    [-2, 6],
    [8, -4]
])


print(inverse_matrix(m))



[[0.1  0.15]
 [0.2  0.05]]


# Eigenvector and eigenvalues:
- $\textbf{A} \in R^{n*n}$, $\textbf{I}$(identity matrix) $\in R^{n*n}, \textbf{v} \in R^n$
- Eigenvalue $(\lambda)$: $det(\textbf{A} - \lambda \textbf{I})$ = 0
- Engenvector $(\textbf{v}): \textbf{Av} = \lambda\textbf{v} \iff (\textbf{A} - \lambda\textbf{I})\textbf{v} = 0$
- Normalized vector: $\frac{\textbf{v}}{\|\textbf{v}\|}$, $v_{i} = \frac{v_{i}}{\sqrt{\sum_{i=1}^{n} v_i^2}}$

$A = \begin{bmatrix}
    0.9 & 0.2\\
    0.1 & 0.8
\end{bmatrix}$

In [25]:
def compute_eigenvalues_eigenvectors(matrix):
    # print('eigenvalues', np.linalg.eigvals(matrix))

    return np.linalg.eig(matrix)

matrix = np.array([
    [0.9, 0.2],
    [0.1, 0.8]
])

print(compute_eigenvalues_eigenvectors(matrix))


(array([1. , 0.7]), array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]]))


# Cosine Similarity

- Data (vector $\textbf{x}, \textbf{y}$): $\textbf{x} = \{x_1, ..., x_N\}$ $\textbf{y} = \{y_1,..., y_N\}$

- Cosine Similarity $cs(\textbf{x}, \textbf{y}) = \frac{\textbf{x}.\textbf{y}}{\|\textbf{x}\| \|\textbf{y}\|} = \frac{\sum_{1}^{n}x_iy_i}{\sqrt{\sum_{1}^{n}x_i^2} \sqrt{\sum_{1}^{n}y_i^2}}$

In [26]:
# Cosine similarity
def compute_cosine(v1, v2):
    dot_product = np.dot(v1, v2)
    distance_product = np.linalg.norm(v1) * np.linalg.norm(v2)

    return dot_product/distance_product

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])

print(compute_cosine(x, y))

0.5773502691896257
